version: '3'

services:
  php:
    build:
      context: .docker/php
    ports:
      - "80:8000"
    volumes:
      - ./:/app
    working_dir: /app
    command: ./artisan serve --host=0.0.0.0

  mysql:
    image: mysql:8
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: crud
      MYSQL_USER: crud
      MYSQL_PASSWORD: crud
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  nodejs:
    image: node:14.15.0-alpine3.10
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    tty: true

volumes:
  mysql-data: